import { Match } from "@g-loot/react-tournament-brackets/dist/src/types";

export const size16: Match[] = [
  {
    id: 260005,
    name: 'Champion',
    nextMatchId: null,
    nextLooserMatchId: undefined,
    tournamentRoundText: '3',
    startTime: 'Date Time',
    state: 'DONE',
    participants: [
      {
        id: '1',
        resultText: null,
        isWinner: false,
        status: null,
        name: 'CHAMPION',
      },
    ],
  },
  {
    id: 260006,
    name: 'Semi Final - Match 1',
    nextMatchId: 260005,
    nextLooserMatchId: undefined,
    tournamentRoundText: '3',
    startTime: 'Date Time',
    state: 'SCORE_DONE',
    participants: [
      {
        id: '1',
        resultText: '1',
        isWinner: true,
        status: 'PLAYED',
        name: 'TBD',
      },
      {
        id: '6',
        resultText: '0',
        isWinner: false,
        status: 'PLAYED',
        name: 'TBD',
      },
    ],
  },
  {
    id: 260013,
    name: 'Semi Final - Match 2',
    nextMatchId: 260005,
    nextLooserMatchId: undefined,
    tournamentRoundText: '3',
    startTime: 'Date Time',
    state: 'SCORE_DONE',
    participants: [
      {
        id: '10',
        resultText: null,
        isWinner: false,
        status: 'NO_SHOW',
        name: 'TBD',
      },
      {
        id: '16',
        resultText: null,
        isWinner: true,
        status: 'WALK_OVER',
        name: 'TBD',
      },
    ],
  },
  {
    id: 260007,
    name: 'Round 2 - Match 1',
    nextMatchId: 260006,
    nextLooserMatchId: undefined,
    tournamentRoundText: '2',
    startTime: 'Date Time',
    state: 'SCORE_DONE',
    participants: [
      {
        id: '1',
        resultText: '0',
        isWinner: false,
        status: 'PLAYED',
        name: 'TBD',
      },
      {
        id: '3',
        resultText: '0',
        isWinner: true,
        status: 'PLAYED',
        name: 'TBD',
      },
    ],
  },
  {
    id: 260010,
    name: 'Round 2 - Match 2',
    nextMatchId: 260006,
    nextLooserMatchId: undefined,
    tournamentRoundText: '2',
    startTime: 'Date Time',
    state: 'SCORE_DONE',
    participants: [
      {
        id: '6',
        resultText: '0',
        isWinner: false,
        status: 'PLAYED',
        name: 'TBD',
      },
      {
        id: '8',
        resultText: '1',
        isWinner: true,
        status: 'PLAYED',
        name: 'TBD',
      },
    ],
  },
  {
    id: 260014,
    name: 'Round 2 - Match 3',
    nextMatchId: 260013,
    nextLooserMatchId: undefined,
    tournamentRoundText: '2',
    startTime: 'Date Time',
    state: 'SCORE_DONE',
    participants: [
      {
        id: '10',
        resultText: '1',
        isWinner: true,
        status: 'PLAYED',
        name: 'TBD',
      },
      {
        id: '12',
        resultText: '0',
        isWinner: false,
        status: 'PLAYED',
        name: 'TBD',
      },
    ],
  },
  {
    id: 260017,
    name: 'Round 2 - Match 4',
    nextMatchId: 260013,
    nextLooserMatchId: undefined,
    tournamentRoundText: '2',
    startTime: 'Date Time',
    state: 'SCORE_DONE',
    participants: [
      {
        id: '14',
        resultText: '1',
        isWinner: true,
        status: 'PLAYED',
        name: 'TBD',
      },
      {
        id: '16',
        resultText: '0',
        isWinner: false,
        status: 'PLAYED',
        name: 'TBD',
      },
    ],
  },
  {
    id: 260011,
    name: 'Round 1 - Match 3',
    nextMatchId: 260010,
    nextLooserMatchId: undefined,
    tournamentRoundText: '1',
    startTime: 'Date Time',
    state: 'WALK_OVER',
    participants: [
      {
        id: '5',
        resultText: null,
        isWinner: false,
        status: null,
        name: 'TBD',
      },
      {
        id: '6',
        resultText: null,
        isWinner: false,
        status: null,
        name: 'TBD',
      },
    ],
  },
  {
    id: 260009,
    name: 'Round 1 - Match 2',
    nextMatchId: 260007,
    nextLooserMatchId: undefined,
    tournamentRoundText: '1',
    startTime: 'Date Time',
    state: 'WALK_OVER',
    participants: [
      {
        id: '3',
        resultText: null,
        isWinner: false,
        status: null,
        name: 'TBD',
      },
      {
        id: '4',
        resultText: null,
        isWinner: false,
        status: null,
        name: 'TBD',
      },
    ],
  },
  {
    id: 260008,
    name: 'Round 1 - Match 1',
    nextMatchId: 260007,
    nextLooserMatchId: undefined,
    tournamentRoundText: '1',
    startTime: 'Date Time',
    state: 'SCORE_DONE',
    participants: [
      {
        id: '1',
        resultText: '1',
        isWinner: true,
        status: 'PLAYED',
        name: 'TBD',
      },
      {
        id: '2',
        resultText: '0',
        isWinner: false,
        status: 'PLAYED',
        name: 'TBD',
      },
    ],
  },
  {
    id: 260015,
    name: 'Round 1 - Match 5',
    nextMatchId: 260014,
    nextLooserMatchId: undefined,
    tournamentRoundText: '1',
    startTime: 'Date Time',
    state: 'WALK_OVER',
    participants: [
      {
        id: '9',
        resultText: null,
        isWinner: false,
        status: null,
        name: 'TBD',
      },
      {
        id: '10',
        resultText: null,
        isWinner: false,
        status: null,
        name: 'TBD',
      },
    ],
  },
  {
    id: 260012,
    name: 'Round 1 - Match 4',
    nextMatchId: 260010,
    nextLooserMatchId: undefined,
    tournamentRoundText: '1',
    startTime: 'Date Time',
    state: 'WALK_OVER',
    participants: [
      {
        id: '7',
        resultText: null,
        isWinner: false,
        status: null,
        name: 'TBD',
      },
      {
        id: '8',
        resultText: null,
        isWinner: false,
        status: null,
        name: 'TBD',
      },
    ],
  },
  {
    id: 260019,
    name: 'Round 1 - Match 8',
    nextMatchId: 260017,
    nextLooserMatchId: undefined,
    tournamentRoundText: '1',
    startTime: 'Date Time',
    state: 'WALK_OVER',
    participants: [
      {
        id: '15',
        resultText: null,
        isWinner: false,
        status: null,
        name: 'TBD',
      },
      {
        id: '16',
        resultText: null,
        isWinner: false,
        status: null,
        name: 'TBD',
      },
    ],
  },
  {
    id: 260018,
    name: 'Round 1 - Match 7',
    nextMatchId: 260017,
    nextLooserMatchId: undefined,
    tournamentRoundText: '1',
    startTime: 'Date Time',
    state: 'WALK_OVER',
    participants: [
      {
        id: '13',
        resultText: null,
        isWinner: false,
        status: null,
        name: 'TBD',
      },
      {
        id: '14',
        resultText: null,
        isWinner: false,
        status: null,
        name: 'TBD',
      },
    ],
  },
  {
    id: 260016,
    name: 'Round 1 - Match 6',
    nextMatchId: 260014,
    nextLooserMatchId: undefined,
    tournamentRoundText: '1',
    startTime: 'Date Time',
    state: 'WALK_OVER',
    participants: [
      {
        id: '11',
        resultText: null,
        isWinner: false,
        status: null,
        name: 'TBD',
      },
      {
        id: '12',
        resultText: null,
        isWinner: false,
        status: null,
        name: 'TBD',
      },
    ],
  },
];
