import { Match } from "@g-loot/react-tournament-brackets/dist/src/types";

export const size16: Match[] = [
  {
    id: 'Round 1 - Match 1',
    name: 'Round 1 - Match 1',
    nextMatchId: 'Round 2 - Match 1',
    nextLooserMatchId: undefined,
    tournamentRoundText: '1',
    startTime: 'Date Time',
    state: 'DONE',
    participants: [
      {
        id: '1',
        resultText: null,
        isWinner: false,
        status: 'DONE',
        name: 'TBD',
      },
      {
        id: '2',
        resultText: null,
        isWinner: false,
        status: 'DONE',
        name: 'TBD',
      },
    ],
  },  
  {
    id: 'Round 1 - Match 2',
    name: 'Round 1 - Match 2',
    nextMatchId: 'Round 2 - Match 1',
    nextLooserMatchId: undefined,
    tournamentRoundText: '1',
    startTime: 'Date Time',
    state: 'DONE',
    participants: [
      {
        id: '3',
        resultText: null,
        isWinner: false,
        status: null,
        name: 'TBD',
      },
      {
        id: '4',
        resultText: null,
        isWinner: false,
        status: null,
        name: 'TBD',
      },
    ],
  },
  {
    id: 'Round 1 - Match 3',
    name: 'Round 1 - Match 3',
    nextMatchId: 'Round 2 - Match 2',
    nextLooserMatchId: undefined,
    tournamentRoundText: '1',
    startTime: 'Date Time',
    state: 'DONE',
    participants: [
      {
        id: '5',
        resultText: null,
        isWinner: false,
        status: null,
        name: 'TBD',
      },
      {
        id: '6',
        resultText: null,
        isWinner: false,
        status: null,
        name: 'TBD',
      },
    ],
  },
  {
    id: 'Round 1 - Match 4',
    name: 'Round 1 - Match 4',
    nextMatchId: 'Round 2 - Match 2',
    nextLooserMatchId: undefined,
    tournamentRoundText: '1',
    startTime: 'Date Time',
    state: 'DONE',
    participants: [
      {
        id: '7',
        resultText: null,
        isWinner: false,
        status: null,
        name: 'TBD',
      },
      {
        id: '8',
        resultText: null,
        isWinner: false,
        status: null,
        name: 'TBD',
      },
    ],
  },
  {
    id: 'Round 1 - Match 5',
    name: 'Round 1 - Match 5',
    nextMatchId: 'Round 2 - Match 3',
    nextLooserMatchId: undefined,
    tournamentRoundText: '1',
    startTime: 'Date Time',
    state: 'DONE',
    participants: [
      {
        id: '9',
        resultText: null,
        isWinner: false,
        status: null,
        name: 'TBD',
      },
      {
        id: '10',
        resultText: null,
        isWinner: false,
        status: null,
        name: 'TBD',
      },
    ],
  },
  {
    id: 'Round 1 - Match 6',
    name: 'Round 1 - Match 6',
    nextMatchId: 'Round 2 - Match 3',
    nextLooserMatchId: undefined,
    tournamentRoundText: '1',
    startTime: 'Date Time',
    state: 'DONE',
    participants: [
      {
        id: '11',
        resultText: null,
        isWinner: false,
        status: null,
        name: 'TBD',
      },
      {
        id: '12',
        resultText: null,
        isWinner: false,
        status: null,
        name: 'TBD',
      },
    ],
  },
  {
    id: 'Round 1 - Match 7',
    name: 'Round 1 - Match 7',
    nextMatchId: 'Round 2 - Match 4',
    nextLooserMatchId: undefined,
    tournamentRoundText: '1',
    startTime: 'Date Time',
    state: 'DONE',
    participants: [
      {
        id: '13',
        resultText: null,
        isWinner: false,
        status: null,
        name: 'TBD',
      },
      {
        id: '14',
        resultText: null,
        isWinner: false,
        status: null,
        name: 'TBD',
      },
    ],
  },
  {
    id: 'Round 1 - Match 8',
    name: 'Round 1 - Match 8',
    nextMatchId: 'Round 2 - Match 4',
    nextLooserMatchId: undefined,
    tournamentRoundText: '1',
    startTime: 'Date Time',
    state: 'DONE',
    participants: [
      {
        id: '15',
        resultText: null,
        isWinner: false,
        status: null,
        name: 'TBD',
      },
      {
        id: '16',
        resultText: null,
        isWinner: false,
        status: null,
        name: 'TBD',
      },
    ],
  },
  {
    id: 'Round 2 - Match 1',
    name: 'Round 2 - Match 1',
    nextMatchId: 'Semi Final 1',
    nextLooserMatchId: undefined,
    tournamentRoundText: '2',
    startTime: 'Date Time',
    state: 'DONE',
    participants: [
      {
        id: 'R2-1',
        resultText: null,
        isWinner: false,
        status: 'DONE',
        name: 'TBD',
      },
      {
        id: 'R2-2',
        resultText: null,
        isWinner: false,
        status: 'DONE',
        name: 'TBD',
      },
    ],
  },
  {
    id: 'Round 2 - Match 2',
    name: 'Round 2 - Match 2',
    nextMatchId: 'Semi Final 1',
    nextLooserMatchId: undefined,
    tournamentRoundText: '2',
    startTime: 'Date Time',
    state: 'DONE',
    participants: [
      {
        id: 'R2-3',
        resultText: null,
        isWinner: false,
        status: 'DONE',
        name: 'TBD',
      },
      {
        id: 'R2-4',
        resultText: null,
        isWinner: false,
        status: 'DONE',
        name: 'TBD',
      },
    ],
  },
  {
    id: 'Round 2 - Match 3',
    name: 'Round 2 - Match 3',
    nextMatchId: 'Semi Final 2',
    nextLooserMatchId: undefined,
    tournamentRoundText: '2',
    startTime: 'Date Time',
    state: 'DONE',
    participants: [
      {
        id: 'R2-5',
        resultText: null,
        isWinner: false,
        status: 'DONE',
        name: 'TBD',
      },
      {
        id: 'R2-6',
        resultText: null,
        isWinner: false,
        status: 'DONE',
        name: 'TBD',
      },
    ],
  },
  {
    id: 'Round 2 - Match 4',
    name: 'Round 2 - Match 4',
    nextMatchId: 'Semi Final 2',
    nextLooserMatchId: undefined,
    tournamentRoundText: '2',
    startTime: 'Date Time',
    state: 'DONE',
    participants: [
      {
        id: 'R2-7',
        resultText: null,
        isWinner: false,
        status: 'DONE',
        name: 'TBD',
      },
      {
        id: 'R2-8',
        resultText: null,
        isWinner: false,
        status: 'DONE',
        name: 'TBD',
      },
    ],
  },
  {
    id: 'Semi Final 1',
    name: 'Semi Final 1',
    nextMatchId: 'Champion',
    nextLooserMatchId: undefined,
    tournamentRoundText: '3',
    startTime: 'Date Time',
    state: 'DONE',
    participants: [
      {
        id: 'SF1-1',
        resultText: null,
        isWinner: false,
        status: 'DONE',
        name: 'TBD',
      },
      {
        id: 'SF1-2',
        resultText: null,
        isWinner: false,
        status: 'DONE',
        name: 'TBD',
      },
    ],
  },
  {
    id: 'Semi Final 2',
    name: 'Semi Final 2',
    nextMatchId: 'Champion',
    nextLooserMatchId: undefined,
    tournamentRoundText: '3',
    startTime: 'Date Time',
    state: 'DONE',
    participants: [
      {
        id: 'SF2-1',
        resultText: null,
        isWinner: false,
        status: 'DONE',
        name: 'TBD',
      },
      {
        id: 'SF2-2',
        resultText: null,
        isWinner: false,
        status: 'DONE',
        name: 'TBD',
      },
    ],
  },
  {
    id: 'Champion',
    name: 'Champion',
    nextMatchId: null,
    nextLooserMatchId: undefined,
    tournamentRoundText: '3',
    startTime: 'Date Time',
    state: 'DONE',
    participants: [
      {
        id: '1',
        resultText: null,
        isWinner: false,
        status: null,
        name: 'CHAMPION',
      },
    ],
  }
];
