export const matchs = [
  {
    id: '1',
    game: 'Counter Striker',
    date: '2023/04/24',
    time: '14:00',
    participants: ['eu', 'tu', 'ele', 'nós', 'vós', 'eles'],
    voiceChannel: 'https://discord.gg/123456',
    description: 'Lorem ipsum dolor sit a',
  },
  {
    id: '2',
    game: 'Counter Striker',
    date: '2023/04/24',
    time: '14:00',
    participants: ['eu', 'tu', 'ele', 'nós', 'vós', 'eles'],
    voiceChannel: 'https://discord.gg/123456',
    description: 'Lorem ipsum dolor sit a',
  },
  {
    id: '3',
    game: 'Counter Striker',
    date: '2023/04/24',
    time: '14:00',
    participants: ['eu', 'tu', 'ele', 'nós', 'vós', 'eles'],
    voiceChannel: 'https://discord.gg/123456',
    description: 'Lorem ipsum dolor sit a',
  },
  {
    id: '4',
    game: 'Counter Striker',
    date: '2023/04/24',
    time: '14:00',
    participants: ['eu', 'tu', 'ele', 'nós', 'vós', 'eles'],
    voiceChannel: 'https://discord.gg/123456',
    description: 'Lorem ipsum dolor sit a',
  },
  {
    id: '5',
    game: 'Counter Striker',
    date: '2023/04/24',
    time: '14:00',
    participants: ['eu', 'tu', 'ele', 'nós', 'vós', 'eles'],
    voiceChannel: 'https://discord.gg/123456',
    description: 'Lorem ipsum dolor sit a',
  },
  {
    id: '6',
    game: 'Counter Striker',
    date: '2023-06-13',
    time: '17:00',
    participants: ['eu', 'tu', 'ele', 'nós', 'vós', 'eles'],
    voiceChannel: 'https://discord.gg/123456',
    description: 'Lorem ipsum dolor sit a',
  },
  {
    id: '7',
    game: 'Counter Striker',
    date: '2023-06-13',
    time: '14:37',
    participants: ['eu', 'tu', 'ele', 'nós', 'vós', 'eles'],
    voiceChannel: 'https://discord.gg/123456',
    description: 'Lorem ipsum dolor sit a',
  },
]